name: Unzip File on Push

on:
  push:
    paths:
      - 'three-learn.zip'  # مسیر فایل زیپ در ریشه مخزن

jobs:
  unzip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Unzip the file
      run: |
        mkdir extracted_files
        unzip three-learn.zip -d extracted_files/  # فایل zip شما در ریشه مخزن است
